name: E2E SLSA3 go push main

on: 
  schedule:
    - cron: '0 2 * * *'
  # Too test.
  workflow_dispatch:

permissions: read-all

env:
  TARGET_REPOSITORY: slsa-framework/slsa-github-generator-go
  THIS_FILE: e2e.go.slsa3.yml

jobs:
  #TODO: support multiple config files.
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: slsa-framework/slsa-github-generator-go/.github/workflows/slsa3_builder.yml@main
    with:
      go-version: 1.18

  run-if-failed:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'failure')
    env:
      GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/e2e-runs.sh
          
  verify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          set -euo pipefail
          
          echo "TODO: slsa-verify for all released and for HEAD"
