on:
  workflow_dispatch:

permissions: read-all

jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:
      # Install at tag.
      - uses: slsa-framework/slsa-verifier/actions/installer@v2.0.0
      - run: |
          version=$(slsa-verifier version 2>&1 | grep GitVersion | cut -d ':' -f2 | tr -d "[:space:]")
          [ "$version" == "2.0.0" ]
      
      # Install at commit.
      - uses: slsa-framework/slsa-verifier/actions/installer@936dc46aca3ed973d542a09d2a9d890705ce5011
      - run: |
          version=$(slsa-verifier version 2>&1 | grep GitVersion | cut -d ':' -f2 | tr -d "[:space:]")
          [ "$version" == "2.0.0" ]
