on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: read-all

concurrency: "e2e.generic.workflow_dispatch.main.large-subjects.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-dispatch.sh

  build:
    if: github.event_name == 'workflow_dispatch'
    outputs:
      binary-name: ${{ steps.build.outputs.binary-name }}
      handle: ${{ steps.patchedhandle.outputs.handle }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@95c9bf48d0c570bb3e28e57108f3450cd67c1a44 # tag=v2.0.0
        with:
          bazelisk-version: "1.11"
      - name: Build artifact
        id: build
        run: |
          bazelisk build //:hello
          cp bazel-bin/hello_/hello . # Copy binary from Bazel path to root
          echo "binary-name=hello" >> "${GITHUB_OUTPUT}"
      - name: Upload binary
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ steps.build.outputs.binary-name }}
          path: ${{ steps.build.outputs.binary-name }}
          if-no-files-found: error
          retention-days: 5
      - name: Generate hash
        shell: bash
        id: hash
        env:
          BINARY_NAME: ${{ steps.build.outputs.binary-name }}
        run: |
          set -euo pipefail

          outfile="tmp_file"
          sha256sum "$BINARY_NAME" > "$outfile"
          cat "$outfile" | base64 -w0 > digests.txt

      - name: Share the file
        uses: slsa-framework/slsa-github-generator/actions/generator/generic/create-base64-subjects-from-file@main
        with:
          path: digests.txt

      - name: Alter the sha256
        shell: bash
        id: patchedhandle
        run: |
          set -euo pipefail

          # NOTE: hash of the file is 19e01912fdc57ec7723b121ec77cd3f897f5771a517ddc0976e19627f8d376f5
          patched_handle=$(cat digests.txt | jq '.sha256 = "19e01912fdc57ec7723b121ec77cd3f897f5771a517ddc0976e19627f8d376f6"')
          echo "handle=$patched_handle" >> "${GITHUB_OUTPUT}"

  provenance:
    if: github.event_name == 'workflow_dispatch'
    needs: [build]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects-as-file: "${{ needs.build.outputs.handle }}"
      compile-generator: true

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build, provenance]
    if: github.event_name == 'workflow_dispatch' && needs.build.result == 'success' && needs.provenance.result == 'failure'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build, provenance]
    if: always() && github.event_name == 'workflow_dispatch' && (needs.build.result == 'failure' || needs.provenance.result == 'success')
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
