name: E2E SLSA3 go push main

on: 
  schedule:
    - cron: '0 2 * * *'
  # Too test.
  workflow_dispatch:

permissions: read-all

env:
  TARGET_REPOSITORY: slsa-framework/slsa-github-generator-go
  THIS_FILE: e2e.go.slsa3.yml

jobs:
  #TODO: support multiple config files.
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 1
#     permissions:
#       id-token: write # For signing.
#       contents: write # For asset uploads.
#     uses: slsa-framework/slsa-github-generator-go/.github/workflows/slsa3_builder.yml@main
#     with:
#       go-version: 1.18

  run-if-failed:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'failure')
    env:
      GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
    steps:
      - run: |
          set -euo pipefail

          ./.github/workflows/e2e-runs.sh
          
