on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  create:

permissions: read-all

concurrency: "e2e-nodejs-create-main-default-slsa3"

env:
  PAT_TOKEN: ${{ secrets.E2E_NODEJS_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  # NOTE: must be kept in sync with 'if' expressions.
  DEFAULT_VERSION: v39.0.0

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      # Bumps the package version pushes, creates a git tag, and pushes the tag.
      - run: ./.github/workflows/scripts/e2e-nodejs-push.sh

  # Shim determines if the rest of the workflow should run.
  # NOTE: it should only use the `if` to determine this and all downstream jobs
  #      should depend on this job.
  shim:
    # NOTE: this must be kept in sync with the if-failed job.
    if: github.event_name == 'create' && startsWith(github.ref, "refs/tags/v39")
    run: |
      echo "event: ${GITHUB_EVENT_NAME}"
      echo "ref: ${GITHUB_REF}"

  build:
    needs: [shim]
    permissions:
      id-token: write # For signing.
      contents: read # For repo checkout of private repos.
      actions: read # For getting workflow run on private repos.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@main
    with:
      directory: nodejs/e2e-nodejs-create-main-default-slsa3
      node-version: 16
      run-scripts: "ci, build"

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: publish
        id: publish
        uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@main
        with:
          access: public
          node-auth-token: ${{ secrets.E2E_NODE_ACCESS_TOKEN }}
          package-name: ${{ needs.build.outputs.package-name }}
          package-download-name: ${{ needs.build.outputs.package-download-name }}
          package-download-sha256: ${{ needs.build.outputs.package-download-sha256 }}
          provenance-name: ${{ needs.build.outputs.provenance-name }}
          provenance-download-name: ${{ needs.build.outputs.provenance-download-name }}
          provenance-download-sha256: ${{ needs.build.outputs.provenance-download-sha256 }}

  verify:
    runs-on: ubuntu-latest
    needs: [build, publish]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set up Node environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16
      # NOTE: for building the verifier.
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.18"
      - run: ./.github/workflows/scripts/e2e.nodejs.default.verify.sh

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build, publish, verify]
    if: needs.build.result == 'success' && needs.publish.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build, publish, verify]
    if: always() && github.event_name == 'create' && startsWith(github.ref, "refs/tags/v39") && (needs.build.result == 'failure' || needs.publish.result == 'failure' || needs.verify.result == 'failure')
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
