name: go push main SLSA3

on: 
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions: read-all

env:
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator-go
  #ISSUE_REPOSITORY: laurentsimon/slsa-on-github-test
  THIS_FILE: e2e.go.push.main.slsa3.yml

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-push.sh
    
  #TODO: support multiple config files.
  build:
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: slsa-framework/slsa-github-generator-go/.github/workflows/slsa3_builder.yml@main
    with:
      go-version: 1.18
      #TODO: support different options
  
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           exit 1
    
  verify:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event.head_commit.message == github.workflow
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.17'
      - run: |
          set -euo pipefail
        
          ./.github/workflows/scripts/e2e-verify.sh
          
  if-failed:
    runs-on: ubuntu-latest
    needs: [build,verify]
    if: always() && github.event_name == 'push' && github.event.head_commit.message == github.workflow && (needs.build.result == 'failure' || needs.verify.result == 'failure')
    env:
      GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-report-failure.sh
