on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

concurrency: "e2e.delegator-generic.release.main.default.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  DEFAULT_VERSION: v42.0.0

jobs:
  # Release
  ################################################################################
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: create
        run: ./.github/workflows/scripts/e2e-create-release.sh

  if-release-failed:
    runs-on: ubuntu-latest
    needs: [release]
    if: always() && github.event_name == 'schedule' && needs.release.result != 'success'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-failure.sh

  # Main workflow
  ################################################################################
  shim:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.ref_type == 'tag'
    outputs:
      continue: ${{ steps.verify.outputs.continue }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: verify
        run: ./.github/workflows/scripts/e2e-verify-release.sh

  build:
    needs: [shim]
    if: needs.shim.outputs.continue == 'yes' && github.event_name == 'release' && github.ref_type == 'tag'
    permissions:
      id-token: write # For signing
      contents: write # For asset uploads
      packages: write # To write to github packages
      actions: read
    # v1.0.0 uses the delegator_generic_slsa3.yml
    # See https://github.com/slsa-framework/example-trw/blob/v1.0.0/.github/workflows/builder_example_slsa3.yml
    uses: slsa-framework/example-trw/.github/workflows/builder_example_slsa3.yml@v1.0.0
    with:
      artifact: my-artifact
      content: "hello world delegator_generic_slsa3"
    secrets:
      # NOTE: this password is set to 'delegator-password'.
      password: ${{ secrets.DELEGATOR_PASSWORD }}

  verify:
    runs-on: ubuntu-latest
    needs: [shim, build]
    if: needs.shim.outputs.continue == 'yes' && github.event_name == 'release' && github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: "${{ needs.build.outputs.artifact }}" # NOTE: This is 'my-artifact'.
      - uses: slsa-framework/example-trw/download/attestation@v1.0.0 # Use same version as the builder.
        with:
          name: "${{ needs.build.outputs.provenance-download-name }}"
          sha256: "${{ needs.build.outputs.provenance-download-sha256 }}"
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.18"
      - env:
          BINARY: "${{ needs.build.outputs.artifact }}"
          PROVENANCE: "${{ needs.build.outputs.provenance-download-name }}/${{ needs.build.outputs.artifact }}.build.slsa" # This is defined by the builder.
          BUILDER_ID: "https://github.com/slsa-framework/example-trw/.github/workflows/builder_example_slsa3.yml"
          BUILDER_TAG: "v1.0.0"
        run: ./.github/workflows/scripts/e2e.delegator.default.verify.sh

  # if-succeeded:
  #   runs-on: ubuntu-latest
  #   needs: [shim, build, verify]
  #   if: needs.shim.outputs.continue == 'yes' && github.event_name == 'release' && github.ref_type == 'tag' && needs.build.result == 'success' && needs.verify.result == 'success'
  #   steps:
  #     - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
  #     - run: ./.github/workflows/scripts/e2e-report-success.sh

  # if-failed:
  #   runs-on: ubuntu-latest
  #   needs: [shim, build, verify]
  #   if: always() && needs.shim.outputs.continue == 'yes' && github.event_name == 'release' && github.ref_type == 'tag' && (needs.build.result == 'failure' || needs.verify.result == 'failure')
  #   steps:
  #     - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
  #     - run: ./.github/workflows/scripts/e2e-report-failure.sh
