on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions: read-all

env:
  # UPDATE ON RELEASE: version.
  LATEST_VERSION: v2.0.1
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-verifier

jobs:
  installer:
    runs-on: ubuntu-latest
    steps:
      # Install at tag.
      # UPDATE ON RELEASE: tag.
      - uses: slsa-framework/slsa-verifier/actions/installer@v2.0.1
      - run: |
          version=$(slsa-verifier version 2>&1 | grep GitVersion | cut -d ':' -f2 | tr -d "[:space:]")
          [ "$version" == "${LATEST_VERSION:1}" ]

      - run: |
          binary_path=$(which slsa-verifier)
          rm -rf "$binary_path"

      # Install at commit.
      # UPDATE ON RELEASE: commit sha.
      - uses: slsa-framework/slsa-verifier/actions/installer@fb8ab2af45ceb658c0643e120363020bf0bbb3e4
      - run: |
          version=$(slsa-verifier version 2>&1 | grep GitVersion | cut -d ':' -f2 | tr -d "[:space:]")
          [ "$version" == "${LATEST_VERSION:1}" ]

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [installer]
    if: needs.installer.result == 'success'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [installer]
    if: always() && needs.installer.result == 'failure'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
