on:
  # Only triggered manually for pre-release.
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    # Update this line: the repo name and the reference
    uses: ianlewis/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0-rc.2
    with:
      go-version: 1.18
      config-file: .github/configs-go/config-noldflags.yml

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build]
    if: needs.build.result == 'success'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: |
          set -euo pipefail

          echo "This test should fail"
          exit 1
