name: E2E SLSA3 go push main

on: 
  schedule:
    - cron: '0 2 * * *'
  # Too test.
  workflow_dispatch:

permissions: read-all

env:
  TARGET_REPOSITORY: slsa-framework/slsa-github-generator-go
  WORKFLOW_NAME: "E2E SLSA3 go push main"
  THIS_FILE: e2e.go.slsa3.yml

jobs:
  #TODO: support multiple config files.
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: slsa-framework/slsa-github-generator-go/.github/workflows/slsa3_builder.yml@main
    with:
      go-version: 1.18

  run-if-failed:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'failure')
    env:
      GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
    steps:
      - run: |
          #TODO: create issue on the repo about the failure.
          RUN_DATE=$(date --utc)
          
          cat << EOF > BODY
          Repo: https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_REF_NAME
          Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Workflow name: $WORKFLOW_NAME
          Workflow file: https://github.com/${{ github.repository }}/tree/main/.github/workflows/$THIS_FILE
          Trigger: $GITHUB_EVENT_NAME
          Branch: main
          Date: $RUN_DATE
          EOF
          
          gh issue create -t "Run failure: $WORKFLOW_NAME" -F ./BODY -R "$TARGET_REPOSITORY"  
