on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions: read-all

env:
  PAT_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  # ISSUE_REPOSITORY: laurentsimon/slsa-on-github-test
  # WARNING: update build job if CONFIG_FILE changes.
  CONFIG_FILE: ../invalid/path.yml

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@main
    with:
      go-version: 1.18
      # We cannot use ${{ env.CONFIG_FILE }} because env variables are not available.
      config-file: ../invalid/path.yml
      compile-builder: true

  #   build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - run: |
  #           exit 1

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build]
    # NOTE: The workflow is allowed to run for other event types but don't post
    # to issues unless it's a schedule event.
    if: github.event_name == 'schedule' && needs.build.result == 'success'
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
      - run: ./.github/workflows/scripts/badges/update-failing.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build]
    # NOTE: The workflow is allowed to run for other event types but don't post
    # to issues unless it's a schedule event.
    if: always() && github.event_name == 'schedule' && needs.build.result == 'failure'
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: ./.github/workflows/scripts/e2e-report-success.sh
      - run: ./.github/workflows/scripts/badges/update-passing.sh
