name: Build using slsa-github-generator
on: 
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  
jobs:
  build:
    outputs:
      digest: ${{ steps.hash.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazelisk build //:hello
      - uses: actions/upload-artifact@v3
        with:
          path: bazel-bin/hello_/hello
      - name: "generate hash"
        shell: bash
        id: hash
        run: |
          set -euo pipefail
          DIGEST=$(sha256sum bazel-bin/hello_/hello)
          DIGEST="${DIGEST//'%'/'%25'}"
          DIGEST="${DIGEST//$'\n'/'%0A'}"
          DIGEST="${DIGEST//$'\r'/'%0D'}"
          echo "::set-output name=digest::$DIGEST"
  provenance:
    needs: [build]
    permissions:
      id-token: write
      contents: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/slsa2_provenance.yml@main
    with:
      subjects: "${{ needs.build.outputs.digest }}"
